#include "atom.h"

lmptools::Atom::Atom(Int32 atomID, Int32 molID, Int32 type, Str element,
                     Float64 mass, Float64 charge, Float64 radius,
                     Float64 diameter, const Vec3<Float64> &omega,
                     const Vec3<Float64> &angmom, const Vec3<Float64> &torque,
                     const Vec3<Float64> &position,
                     const Vec3<Float64> &positionScaled,
                     const Vec3<Float64> &positionUnwrapped,
                     const Vec3<Int32> &imageID, const Vec3<Float64> &velocity,
                     const Vec3<Float64> &force, const Vec3<Float64> &dipole)
    : atomID{atomID},
      molID{molID},
      type{type},
      element(std::move(element)),
      mass{mass},
      charge{charge},
      radius{radius},
      diameter{diameter},
      omega{omega},
      angmom{angmom},
      torque{torque},
      position{position},
      positionScaled{positionScaled},
      positionUnwrapped{positionUnwrapped},
      imageID{imageID},
      velocity{velocity},
      force{force},
      dipole{dipole} {}
