name: changelog_check

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: dangoslen/changelog-enforcer@v3
        with:
          missingUpdateErrorMessage: "CHANGELOG.md not updated"
