name: Changelog reminder

on:
  workflow_call:
    inputs:
      changelog_updated:
        description: Boolean flag to show whether changelog was updated or not
        type: boolean
        default: false

jobs:
  remind:
    name: Changelog reminder
    runs-on: ubuntu-latest
    steps:
      - name: Changelog Reminder
        if: ${{ !inputs.changelog_updated }}
        uses: peterjgrainger/action-changelog-reminder@v1.3.0
        with:
          changelog_regex: "CHANGELOG.md"
          customPrMessage: |
            Please update the [`CHANGELOG.md`](/venkatBala/lmptools/blob/master/CHANGELOG.md) with the changes being made as part of this PR in the [Unreleased] section
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
