name: changelog

on:
  pull_request:

jobs:
  changelog_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: dangoslen/changelog-enforcer@v3
        with:
          missingUpdateErrorMessage: "CHANGELOG.md not updated"

  changelog:
    needs: changelog_check
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@master

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.18.5"

      - name: Download changelog parser
        uses: actions/checkout@v3
        with:
          repository: venkatBala/changelog
          path: "./changelog"

      - name: Compile changelog parser
        run: |
          go build
          go install
          export PATH=$PATH:$HOME/go/bin
        working-directory: ./changelog

      - name: Parse Unreleased header to determine version update
        id: update_version
        run: |
          # Current version
          # Read current version from file
          VERSION=$(cat ./VERSION)

          MAJOR_VERSION=$(echo $VERSION | cut -d"." -f1)
          MINOR_VERSION=$(echo $VERSION | cut -d"." -f2)
          PATCH_VERSION=$(echo $VERSION | cut -d"." -f3)

          # Parse the headers into a shell array
          IFS=$'\n' read -r -d '' -a HEADERS < <( ~/go/bin/changelog show Unreleased | grep '^###' | cut -d" " -f2 && printf '\0' )
          NUM_HEADERS=${#HEADERS[@]}

          if [[ $NUM_HEADERS -eq 0 ]]; then
            echo "CHANGELOG.md not updated"
            exit 1
          fi

          echo "Headers parsed: ${HEADERS[@]}"

          echo '::set-output name=message::noop'

          # Check if the parsed headers are either Added, Changed or Removed
          if [[ "${HEADERS[@]}" =~ "Added" ]] || [[ "${HEADERS[@]}" =~ "Changed" ]] || [[ "${HEADERS[@]}" =~ "Removed" ]]
          then
            echo '::set-output name=message::Minor version will be incremented'
            MINOR_VERSION=$((MINOR_VERSION+1))
          fi

          if [[ "${HEADERS[@]}" =~ "Fixed" ]] || [[ "${HEADERS[@]}" =~ "Security" ]]
          then
            echo '::set-output name=message::Patch version will be incremented'
            PATCH_VERSION=$((PATCH_VERSION+1))
          fi

          # Update version
          VERSION=${MAJOR_VERSION}.${MINOR_VERSION}.${PATCH_VERSION}
          echo $VERSION > ./VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create release changelog
        id: update_changelog
        run: |
          VERSION=$(cat ./VERSION)
          ~/go/bin/changelog release $VERSION -c https://github.com/venkatBala/lmptools/changelog/compare/$GITHUB_SHA...develop -f ./CHANGELOG.md

      - name: Commit changes
        run: |
          git checkout $GITHUB_HEAD_REF
          git config user.name "LMPToolsOpsBot"
          git config user.email "112046753+LMPToolsOpsBot@users.noreply.github.com"
          git add .
          git commit -m "changelog/version updated to ${{ env.VERSION }}"
          git push origin $GITHUB_HEAD_REF --force
