name: Clang Format Check
on:
  - "push"
  - "pull_request"

jobs:
  clang-formatting-check:
    name: Clang format check
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        path:
          - '${{ github.workspace }}/cpp/src'
          - '${{ github.workspace }}/cpp/include'
    steps:
      - uses: actions/checkout@v3

      - name: Run clang-format check
        uses: jidicula/clang-format-action@v4.9.0
        with:
          clang-format-version: '14'
          check-path: ${{ matrix.path }}
