name: tests

on:
  pull_request:
    paths-ignore:
      - ".github/**"
      - "examples/**"
      - "*.md"
  workflow_run:
    workflows: [changelog]
    types: [completed]

jobs:
  tests:
    runs-on: "ubuntu-latest"
    continue-on-error: false
    outputs:
      release: ${{ steps.push.outputs.release }}
    steps:
      - name: Check out head
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          token: ${{ secrets.ADMIN_TOKEN }}

      - name: Install GCC toolchain
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 11
          platform: x64

      - name: Install Google Tests
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtest-dev

      - name: Configure CMake
        run: |
          cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: |
          cmake --build ${{ github.workspace }}/build --config Debug

      - name: Run tests and measure coverage
        run: |
          ctest -v

  release:
    needs: tests
    if: github.ref == 'refs/heads/develop'
    uses: venkatBala/lmptools/.github/workflows/release.yml@develop
    secrets: inherit
    with:
      prerelease: true
